import {
  CalendarDays,
  Flashlight,
  FlashlightOff,
  Droplet,
  Dumbbell,
  Check,
  Drumstick,
  Flame,
  Wheat,
  Camera,
  ChartNoAxesColumn,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  GlassWater,
  LogOut,
  Palette,
  Target,
  UtensilsCrossed,
  Minus,
  NotebookText,
  Plus,
  Scale,
  ScanBarcode,
  Search,
  Star,
  UserRound,
  X,
  type LucideIcon,
} from "lucide-react";

// Ein Icon-Set für die ganze App (DESIGN.md: Lucide, 1.75px Strich, 24px Standard).
const ICONS = {
  back: ChevronLeft,
  forward: ChevronRight,
  expand: ChevronDown,
  barcode: ScanBarcode,
  camera: Camera,
  search: Search,
  star: Star,
  remove: X,
  add: Plus,
  minus: Minus,
  water: GlassWater,
  calendar: CalendarDays,
  diary: NotebookText,
  stats: ChartNoAxesColumn,
  weight: Scale,
  profile: UserRound,
  target: Target,
  meals: UtensilsCrossed,
  palette: Palette,
  logout: LogOut,
  flame: Flame,
  protein: Drumstick,
  carbs: Wheat,
  fat: Droplet,
  training: Dumbbell,
  check: Check,
  torch: Flashlight,
  torchOff: FlashlightOff,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export function Icon({ name, size = 24, filled = false, className }: { name: IconName; size?: number; filled?: boolean; className?: string }) {
  const Component = ICONS[name];
  return <Component size={size} strokeWidth={1.75} fill={filled ? "currentColor" : "none"} className={className} aria-hidden />;
}
